### ISSUE TITLE
Not able to create docker-compose with ebook-chat source code.

### ISSUE THREAD

**Issue by isushilksharma** [jorgeacetozi/ebook-chat-app-spring-websocket-cassandra-redis#5]
Help me creating docker-compose of whole application - including ebook-chat application.

**Comment by jorgeacetozi** [comment]
Hi, sorry for my delayed answer.
Unfortunately, I can't help you if don't provide a full description of the issue. I hope you got this working on your machine. If not, please open another issue with a full description of the issue.
